In [1]:
import json
import networkx as nx
import numpy as np

def validate_graph(G):
    print("节点特征验证:")
    for node in G.nodes(data=True):
        print(f"Node {node[0]}: features={node[1]['features']}")

    print("\n边权重验证:")
    for edge in G.edges(data=True):
        print(f"Edge {edge[0]}-{edge[1]}: weight={edge[2]['weight']}")



def load_graph_from_json(json_path):
    with open(json_path) as f:
        data = json.load(f)

    G = nx.Graph()
    for node in data['nodes']:
        G.add_node(node['id'], features=node['features'])

    for edge in data['edges']:
        G.add_edge(edge['source'], edge['target'], weight=edge.get('weight', 1.0))

    return G

if __name__ == "__main__":
    G = load_graph_from_json('graph_data.json')
    validate_graph(G)

    # 特征相似度验证
    from sklearn.metrics.pairwise import cosine_similarity
    features = [G.nodes[n]['features'] for n in sorted(G.nodes)]
    sim_matrix = cosine_similarity(features)
    print("\n余弦相似度矩阵:")
    print(np.round(sim_matrix, 3))


节点特征验证:
Node 0: features=[1.0, 0.0, 0.2]
Node 1: features=[0.9, 0.1, 0.3]
Node 2: features=[0.85, 0.15, 0.25]
Node 3: features=[0.2, 0.8, 0.9]
Node 4: features=[0.3, 0.7, 0.85]

边权重验证:
Edge 0-1: weight=0.9
Edge 0-2: weight=0.8
Edge 0-3: weight=0.2
Edge 1-2: weight=0.85
Edge 3-4: weight=0.95

余弦相似度矩阵:
[[1.    0.987 0.982 0.305 0.404]
 [0.987 1.    0.997 0.455 0.547]
 [0.982 0.997 1.    0.47  0.558]
 [0.305 0.455 0.47  1.    0.994]
 [0.404 0.547 0.558 0.994 1.   ]]
